spring:
  datasource:
    url: jdbc:h2:mem:healthcare;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    name: healthcare
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  liquibase:
    user: sa
    password:
    url: jdbc:h2:mem:healthcare;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    change-log: classpath:liquibase/master.xml
  h2:
    console:
      enabled: true
